/**
 * ATMFinderAPI
 * Find nearest ATM at a location
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@wipro.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ATMRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-25T08:25:26.388Z")
public class ATMRequest   {
  @SerializedName("lat")
  private String lat = null;

  @SerializedName("long")
  private String _long = null;

  public ATMRequest lat(String lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Latitude of user location
   * @return lat
  **/
  @ApiModelProperty(example = "null", value = "Latitude of user location")
  public String getLat() {
    return lat;
  }

  public void setLat(String lat) {
    this.lat = lat;
  }

  public ATMRequest _long(String _long) {
    this._long = _long;
    return this;
  }

   /**
   * Longitude of user location
   * @return _long
  **/
  @ApiModelProperty(example = "null", value = "Longitude of user location")
  public String getLong() {
    return _long;
  }

  public void setLong(String _long) {
    this._long = _long;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ATMRequest aTMRequest = (ATMRequest) o;
    return Objects.equals(this.lat, aTMRequest.lat) &&
        Objects.equals(this._long, aTMRequest._long);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lat, _long);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ATMRequest {\n");
    
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    _long: ").append(toIndentedString(_long)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

