/**
 * ATMFinderAPI
 * Find nearest ATM at a location
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@wipro.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ATMResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-25T08:25:26.388Z")
public class ATMResponse   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("Address")
  private String address = null;

  @SerializedName("lat")
  private String lat = null;

  @SerializedName("lon")
  private String lon = null;

  public ATMResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id of ATM
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Id of ATM")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ATMResponse address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Address of ATM
   * @return address
  **/
  @ApiModelProperty(example = "null", value = "Address of ATM")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public ATMResponse lat(String lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Latitude of ATM
   * @return lat
  **/
  @ApiModelProperty(example = "null", value = "Latitude of ATM")
  public String getLat() {
    return lat;
  }

  public void setLat(String lat) {
    this.lat = lat;
  }

  public ATMResponse lon(String lon) {
    this.lon = lon;
    return this;
  }

   /**
   * Longitude of ATM
   * @return lon
  **/
  @ApiModelProperty(example = "null", value = "Longitude of ATM")
  public String getLon() {
    return lon;
  }

  public void setLon(String lon) {
    this.lon = lon;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ATMResponse aTMResponse = (ATMResponse) o;
    return Objects.equals(this.id, aTMResponse.id) &&
        Objects.equals(this.address, aTMResponse.address) &&
        Objects.equals(this.lat, aTMResponse.lat) &&
        Objects.equals(this.lon, aTMResponse.lon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, address, lat, lon);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ATMResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

